version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=database
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=ojt_database
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: Dockerfile.sql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
      - MYSQL_DATABASE=ojt_with-data
      - MYSQL_USER=user
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: