version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=database
      - MYSQLNAME=ojt_with-data
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: Dockerfile.sql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=ojt_with-data
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
